apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-data-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      micro: catalog-data
  template:
    metadata:
      labels:
        micro: catalog-data
    spec:
      containers:
        - name: catalogdata
          image: vineetkala11/catalog-data
          ports:
            - containerPort: 8000
          env:
            - name: EUREKA_SERVER
              value: http://eureka-server-service:8761/eureka
            - name: HOST_NAME
              value: catalog-data-service
            - name: REDIS_HOST
              value: redis-service