version: '3'
services:
  eureka-server:
    image: "eureka-server"
    ports:
      - "8761:8761"
    networks:
      my-network:
        aliases:
          - eureka-server
  zuul-gateway:
    image: "gateway"
    environment:
      - EUREKA_SERVER=http://eureka-server:8761/eureka
      - HOST_NAME=zuul-gateway
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
    networks:
      my-network:
        aliases:
          - zuul-gateway
  catalog-data:
    image: "catalog-data"
    environment:
      - EUREKA_SERVER=http://eureka-server:8761/eureka
      - REDIS_HOST=redis
      - HOST_NAME=catalog-data
    ports:
      - "8000"
    depends_on:
      - eureka-server
      - redis
    networks:
      my-network:
        aliases:
          - catalog-data
  catalog-service:
    image: "catalog-service"
    environment:
      - EUREKA_SERVER=http://eureka-server:8761/eureka
      - HOST_NAME=catalog-service
    ports:
      - "8100"
    depends_on:
      - eureka-server
    networks:
      my-network:
        aliases:
          - catalog-service
  redis:
    image: "myredis"
    ports:
      - "6379:6379"
    networks:
      my-network:
        aliases:
          - redis
networks:
    my-network:
        driver: bridge